Qa e
mainfranc/Dev-PY111Omskiy pull request #17
Opened 2021-01-19 15:29 UTC by mainfranc

added tasks for the e-module

2021-01-19 18:57 UTC, EnotYoyo commented on Tasks/e1_depth_first_search.py
> +        while True:
не понял зачем этот цикл.

2021-01-19 19:05 UTC, EnotYoyo requested changes
Дейкстра использует динамическое программирование. Т.е. если Вы посчитали кратчайший путь до одно из вершины, то Вы можете и должны использовать эту информацию для поиска кратчайшего пути к другим вершинам.

2021-01-20 12:26 UTC, mainfranc commented on Tasks/e1_depth_first_search.py
> +        while True:
а, не подчистил код. сейчас поправил этот момент

2021-01-20 20:43 UTC, mainfranc commented on Tasks/e1_depth_first_search.py
> +        while True:
а с дейкстрой - я в принципе его поправил - понял, что перемудрил и основную процедуру, по сути, лишней сделал. Все-таки графы мне тяжеловато даются.

2021-01-22 10:18 UTC, EnotYoyo commented on Tasks/e1_depth_first_search.py
> +            if not (node in v_nodes):
node not in v_nodes

2021-01-22 10:24 UTC, EnotYoyo requested changes
Нужно выбирать минимальную по стоимости вершину.

2021-01-22 10:24 UTC, EnotYoyo commented on Tasks/e2_dijkstra.py
> +                    v_nodes.append(relation_)
Вроде здесь лишнее добавление relation_ в v_nodes, поскольку вы помечаете вершину просмотренной только тогда, когда посмотрели ее соседей.

2021-01-22 10:24 UTC, EnotYoyo commented on Tasks/e2_dijkstra.py
> +                    v_queue.put((result[relation_], relation_))
Следующая вершина выбирается с наименьшей стоимостью пути всегда, а у Вас в очередь добавляются все. На самом деле тут нужно не очередь, а просто пеменная, которая будет служить "следуюшей" вершиной. 

В любом случае добавлять result[relation_] в очередь странно, поскольку всегда можно его получить имея relation_ :)

2021-01-30 07:08 UTC, merged