Qa g
mainfranc/Dev-PY111Omskiy pull request #18
Opened 2021-01-19 16:15 UTC by mainfranc

added g module (sorts)

2021-01-19 18:53 UTC, EnotYoyo requested changes
Как написал - сравните реальное время сортировок разных массивов (уже отсортированного, отсортированного в обратном порядке и случайно распределенного) с помощью 4 сортировок (3 Ваши и одна питоновская). 
После этого зовите еще раз. 

Для сравнения можно использовать модуль timeit

2021-01-19 18:53 UTC, EnotYoyo commented on Tasks/g2_quick_sort.py
> +        base_elem = median(container)
Хотя и это и дает идеальную сортировку, но вычислять медиану с алгоритмической точки зрения не самое эффективное решение.

2021-01-19 18:53 UTC, EnotYoyo commented on Tasks/g2_quick_sort.py
> +    lst_less = []
И создавать новый списки тоже не самое эффективное решение, сортировать нужно было именно исходный список.

2021-01-19 18:53 UTC, EnotYoyo commented on Tasks/g2_quick_sort.py
> +        return container
Я приму это решение, если напишите код, который сравнивает скорость работы встроенной сортировки питона, сортировки пузырьком и этой реализации быстрой сортировки :)

2021-01-19 18:53 UTC, EnotYoyo commented on Tasks/g2_quick_sort.py
> +        return container
И сортировку слиянием сюда же :)

2021-01-19 18:53 UTC, EnotYoyo commented on Tasks/g1_merge_sort.py
> +        left_part = container[0:mid]
Вычислять сред - довольно дорогая операция, подразумевается работа именно с индексами

2021-01-20 20:38 UTC, mainfranc commented on Tasks/g1_merge_sort.py
> +        left_part = container[0:mid]
А почему? тут же вычисляется не медиана, а просто делится длина списка пополам, чтобы получить центральный индекс. Я же просто переменную похоже назвал

2021-01-20 20:39 UTC, mainfranc commented on Tasks/g2_quick_sort.py
> +        return container
Понял, напишу тест для замера)

2021-01-20 20:41 UTC, mainfranc commented on Tasks/g2_quick_sort.py
> +        base_elem = median(container)
я просто вспомнил, что на лекции нам рассказывали про главную проблему быстрой сортировки - что точность ниже. а так да, я сначала задавал base_elem = container[0] - но подумал, что точность тут поможет - но поменяю, как и трехсписочную структуру сортировки

2021-01-22 10:28 UTC, EnotYoyo commented on Tasks/g1_merge_sort.py
> +        left_part = container[0:mid]
Потому что создается копия списка, а это небыстрая операция в контексте алгоритмов.

2021-01-22 10:35 UTC, EnotYoyo approved these changes
Обычно  в замерах скорости берут не минимум, а среднее или медиану :) 
Сортировки приняты.
Надеюсь выводы по эффективному написанию алгоритмов сделаны (что слияние медленнее пузырька получилось)

2021-01-23 09:15 UTC, merged